version: '3.8'

services:
  auth_service:
    container_name: auth_service
    restart: always
    build:
      context: ./auth/
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./auth/.env
    volumes:
      - ./auth/:/auth
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - postgres
      - rabbitmq

  notification_service:
    container_name: notification_service
    restart: always
    build:
      context: notification/
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - notification/.env
    volumes:
      - ./notification/:/notification
    command: bash -c "uvicorn main:app --reload --host 0.0.0.0 --port 8001"
    ports:
      - '8001:8001'
    depends_on:
      - redis
      - rabbitmq

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:latest
    container_name: redis_container
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data
    command: "redis-server --requirepass ${REDIS_PASSWORD} --user ${REDIS_USER}"
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "ping" ]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
