"""confirm email

Revision ID: b5f094f36ba4
Revises: bcc9edadf7b7
Create Date: 2024-12-27 14:04:18.370398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f094f36ba4'
down_revision: Union[str, None] = 'bcc9edadf7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm_email', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirm_email')
    # ### end Alembic commands ###
